# Generated by Django 3.1.7 on 2021-03-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLine',
            fields=[
                ('id_user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=20)),
            ],
        ),
    ]
