# Generated by Django 3.1.7 on 2021-03-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userline',
            name='type_user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userline',
            name='name_user',
            field=models.CharField(max_length=100),
        ),
    ]
