# Generated by Django 3.1.7 on 2021-03-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0002_auto_20210308_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('water_bill', models.IntegerField()),
                ('elect_bill', models.IntegerField()),
                ('img', models.CharField(max_length=50)),
                ('facbook', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=50)),
                ('call', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('star', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('tags', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('free', models.IntegerField()),
                ('qrcode', models.CharField(max_length=50)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.dormitory')),
            ],
        ),
        migrations.CreateModel(
            name='filterDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=False)),
                ('air', models.BooleanField(default=False)),
                ('fan', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('table', models.BooleanField(default=False)),
                ('parking_lot', models.BooleanField(default=False)),
                ('elevators', models.BooleanField(default=False)),
                ('security_camera', models.BooleanField(default=False)),
                ('keycard', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.room')),
            ],
        ),
    ]
