# Generated by Django 3.1.7 on 2021-03-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0003_dormitory_filterdo_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='id_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='loginline.userline'),
            preserve_default=False,
        ),
    ]
