# Generated by Django 3.1.7 on 2021-03-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0004_dormitory_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id_room',
            field=models.CharField(default='', max_length=50),
        ),
    ]
