# Generated by Django 3.1.7 on 2021-03-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0005_room_id_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id_room',
        ),
    ]
