# Generated by Django 3.1.7 on 2021-03-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0006_remove_room_id_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='img',
            field=models.CharField(max_length=200),
        ),
    ]
