# Generated by Django 3.1.7 on 2021-03-10 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0007_auto_20210309_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterdo',
            name='elevators',
        ),
        migrations.RemoveField(
            model_name='filterdo',
            name='keycard',
        ),
        migrations.RemoveField(
            model_name='filterdo',
            name='laundry',
        ),
        migrations.RemoveField(
            model_name='filterdo',
            name='parking_lot',
        ),
        migrations.RemoveField(
            model_name='filterdo',
            name='security_camera',
        ),
        migrations.CreateModel(
            name='filterDormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_lot', models.BooleanField(default=False)),
                ('elevators', models.BooleanField(default=False)),
                ('security_camera', models.BooleanField(default=False)),
                ('keycard', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.dormitory')),
            ],
        ),
    ]
