# Generated by Django 3.1.7 on 2021-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0008_auto_20210311_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdo',
            name='tv',
            field=models.BooleanField(default=False),
        ),
    ]
