# Generated by Django 3.1.7 on 2021-03-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0010_datauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userline',
            name='type_user',
        ),
    ]
