# Generated by Django 3.1.7 on 2021-03-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0012_comment_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.dormitory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.userline')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
