# Generated by Django 3.1.7 on 2021-03-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0014_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.dormitory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.userline')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryNouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.dormitory')),
            ],
        ),
    ]
