# Generated by Django 3.1.7 on 2021-03-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0015_historynouser_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
