# Generated by Django 3.1.7 on 2021-03-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0016_auto_20210314_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='img',
            field=models.CharField(max_length=300),
        ),
    ]
