# Generated by Django 3.1.7 on 2021-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0017_auto_20210316_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='img',
            field=models.CharField(max_length=1000),
        ),
    ]
