# Generated by Django 3.1.7 on 2021-03-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0020_auto_20210316_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1000)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.dormitory')),
            ],
        ),
    ]
