# Generated by Django 3.1.7 on 2021-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0021_imgall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgall',
            name='img',
            field=models.CharField(max_length=5000),
        ),
    ]
