# Generated by Django 3.1.7 on 2021-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0022_auto_20210320_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userline',
            name='id_auto',
            field=models.CharField(default='10001', max_length=10000),
        ),
    ]
