# Generated by Django 3.1.7 on 2021-03-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0023_userline_id_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='img',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.FloatField()),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.dormitory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.userline')),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.BooleanField(default=False)),
                ('book', models.BooleanField(default=False)),
                ('song', models.BooleanField(default=False)),
                ('pray', models.BooleanField(default=False)),
                ('exercise', models.BooleanField(default=False)),
                ('cocial', models.BooleanField(default=False)),
                ('art', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('clean', models.BooleanField(default=False)),
                ('movie', models.BooleanField(default=False)),
                ('homework', models.BooleanField(default=False)),
                ('lie_about', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginline.userline')),
            ],
        ),
    ]
