# Generated by Django 3.1.7 on 2021-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0025_datauser_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='behavior',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
