# Generated by Django 3.1.7 on 2021-03-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0026_datauser_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='distance',
            field=models.FloatField(),
        ),
    ]
