# Generated by Django 3.1.7 on 2021-03-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0026_remove_datauser_yesr'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='yesr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
