# Generated by Django 3.1.7 on 2021-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0027_auto_20210326_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='qrcode',
            field=models.CharField(max_length=100),
        ),
    ]
