# Generated by Django 3.1.7 on 2021-03-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0027_datauser_yesr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauser',
            old_name='yesr',
            new_name='year',
        ),
    ]
