# Generated by Django 3.1.7 on 2021-04-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0029_dormitory_preper'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='id_dor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
