# Generated by Django 3.1.7 on 2021-03-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginline', '0030_datauser_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauser',
            name='year',
        ),
    ]
